version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mypuppet:latest
    command: npm start
    volumes:
      - .:/opt/app
    ports:
      - "8080:3000"
    restart: always
