version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mypuppet:latest
    command: npm start
    volumes:
      - ./package.json:/myapp/package.json
      - ./package-lock.json:/myapp/package-lock.json
      - ./app:/myapp/app
      - ./content:/myapp/content
      - ./output:/myapp/output
    ports:
      - "4242:3000"
    restart: always
